### ISSUE TITLE
Tag the release tweets appropriately

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NuGetPackager#15]
To allow users to filter the twitter feed appropriately we should tag the tweets with

 #MajorRelease, #MinorRelease, #PatchRelease, #Critical

**Comment by distantcam** [comment]
NugetPackager isn't responsible for tweeting. Should this issue be somewhere else?

**Comment by andreasohlund** [comment]
Move it to https://github.com/Particular/ConsoleTweet ?

**Comment by distantcam** [comment]
Copied the issue to ConsoleTweet. Closing this.
