### ISSUE TITLE
Don't create empty nugets/chocos folders

### ISSUE THREAD

**Issue by distantcam** [Particular/NuGetPackager#17]
If there is no package for nuget or chocolatey don't create the folder for the output.

**Comment by SzymonPobiega** [comment]
I think I did that change so that TeamCity artifact directives can work regardless. I think I tried 
```
nugets\*.nupkg
chcos\*.nupkg
```
and when one of the folders does not exist, TC fails the build.

**Comment by SzymonPobiega** [comment]
Closing this @distantcam . Feel free to reopen if you disagree:)
